name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: R unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.69.0
          cache: true
          environments: dev
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Check linters and formatting
        run: pixi run pre-commit-all
      - name: Run unit tests
        run: pixi run test
      - name: Run example notebook
        run: |
          pixi run serve-jupyter nbconvert \
            --to notebook \
            --execute \
            --ExecutePreprocessor.store_widget_state=False \
            --output "${PWD}/out.ipynb" \
            examples/widgets.ipynb

          # Widgets did render successufully as mime bundle
          grep 'application/vnd.jupyter.ywidget-view+json' "${PWD}/out.ipynb"
